// assistant/knowledge.js — knowledge base for the Village Assistant.
// = the original 19 FAQs (faqBase.json, same text as the Hub widget)
// + new entries below. Optional fields per entry:
//   questionKn / answerKn : Kannada question (also used for matching) and answer
//   links                 : [{label, to}] page shortcuts shown as buttons
const base = require('./faqBase.json');

const extra = [
  { id: 'new-schemes-rec', category: 'schemes', question: 'Which government schemes am I eligible for?',
    answer: "Open 'Which schemes suit me?' in the Scheme Checker, enter whatever you know (age, occupation, caste, income, land). The portal ranks the schemes by how well your details match. Then upload your documents on the scheme page for the final verified result.",
    keywords: ['suitable scheme', 'recommend scheme', 'which scheme', 'benefit for me', 'eligible', 'yojane'],
    questionKn: 'ನನಗೆ ಯಾವ ಯೋಜನೆ ಸಿಗುತ್ತದೆ? ಯಾವ ಸರ್ಕಾರಿ ಯೋಜನೆಗೆ ಅರ್ಹ',
    answerKn: "ಯೋಜನೆ ಪರೀಕ್ಷಕದಲ್ಲಿ 'ನನಗೆ ಯಾವ ಯೋಜನೆ ಸೂಕ್ತ?' ತೆರೆಯಿರಿ. ನಿಮ್ಮ ವಯಸ್ಸು, ವೃತ್ತಿ, ಜಾತಿ, ಆದಾಯ, ಜಮೀನು ವಿವರ ನೀಡಿ. ನಿಮಗೆ ಹೊಂದುವ ಯೋಜನೆಗಳ ಪಟ್ಟಿ ಸಿಗುತ್ತದೆ.",
    links: [{ label: 'Which schemes suit me?', to: '/schemes/recommend' }] },
  { id: 'new-pmkisan-docs', category: 'schemes', question: 'What documents are needed for PM-KISAN?',
    answer: 'PM-KISAN needs three documents: Aadhaar card, land ownership record (RTC/Pahani) and bank account details. The applicant name must match on all three. The scheme is for farmers aged 18+ who own agricultural land.',
    keywords: ['pm kisan', 'pmkisan', 'farmer scheme', 'land record', 'rtc', 'pahani', 'kisan samman'],
    questionKn: 'ಪಿಎಂ ಕಿಸಾನ್ ಯೋಜನೆಗೆ ಯಾವ ದಾಖಲೆ ಬೇಕು',
    answerKn: 'ಪಿಎಂ ಕಿಸಾನ್ ಗೆ ಆಧಾರ್ ಕಾರ್ಡ್, ಜಮೀನು ಮಾಲೀಕತ್ವದ ದಾಖಲೆ (ಪಹಣಿ) ಮತ್ತು ಬ್ಯಾಂಕ್ ಖಾತೆ ವಿವರ ಬೇಕು. ಮೂರರಲ್ಲೂ ಹೆಸರು ಒಂದೇ ಆಗಿರಬೇಕು.',
    links: [{ label: 'Check PM-KISAN eligibility', to: '/schemes/pm-kisan/apply' }] },
  { id: 'new-scholarship-docs', category: 'schemes', question: 'What documents are needed for the SC/ST post-matric scholarship?',
    answer: 'You need Aadhaar, caste certificate, income certificate (family income up to ₹2,50,000), education certificate and bank account details. Names must match across the documents. The scholarship is for students aged 16-40 in Class 11 up to postgraduate.',
    keywords: ['scholarship', 'student scheme', 'post matric', 'sc student', 'st student', 'caste certificate', 'income certificate'],
    questionKn: 'ವಿದ್ಯಾರ್ಥಿ ವೇತನಕ್ಕೆ ಯಾವ ದಾಖಲೆ ಬೇಕು',
    answerKn: 'ಆಧಾರ್, ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ, ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (ಕುಟುಂಬ ಆದಾಯ ₹2,50,000 ವರೆಗೆ), ಶೈಕ್ಷಣಿಕ ಪ್ರಮಾಣಪತ್ರ ಮತ್ತು ಬ್ಯಾಂಕ್ ವಿವರ ಬೇಕು.',
    links: [{ label: 'Browse schemes', to: '/schemes/list' }] },
  { id: 'new-ayushman', category: 'schemes', question: 'How is Ayushman Bharat eligibility checked here?',
    answer: 'The portal checks a family document you upload (ration card, SECC extract or income certificate) against the configured rules. It does not query the live government SECC database, so treat the result as a document-based pre-check and confirm at the official centre.',
    keywords: ['ayushman', 'pmjay', 'health insurance', 'health card', 'secc', 'ration card'] },
  { id: 'new-weather', category: 'agri', question: 'How can I get weather alerts for farming?',
    answer: "Open Farm Advisory and choose the 'Weather Alerts' tab, then select your district. You get rule-based alerts from the 5-day forecast for heavy rain, heat, cold and strong wind, each with the values that triggered it.",
    keywords: ['rain', 'forecast', 'storm', 'heat', 'weather', 'climate', 'mausam'],
    questionKn: 'ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ಹೇಗೆ ನೋಡುವುದು ಮಳೆ ಮುನ್ಸೂಚನೆ',
    answerKn: "ಕೃಷಿ ಸಲಹೆ ಪುಟದಲ್ಲಿ 'Weather Alerts' ಟ್ಯಾಬ್ ತೆರೆದು ನಿಮ್ಮ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. ಮಳೆ, ಬಿಸಿಲು, ಚಳಿ ಮತ್ತು ಗಾಳಿಯ ಎಚ್ಚರಿಕೆಗಳು ಸಿಗುತ್ತವೆ.",
    links: [{ label: 'Open Farm Advisory', to: '/agri/advisory' }] },
  { id: 'new-crop', category: 'agri', question: 'Which crop should I grow this season?',
    answer: "In Farm Advisory use 'Crop Recommendation': pick the season (rainy, winter or summer) and your soil type (red, black, laterite, alluvial, sandy loam) to see commonly suitable crops for Karnataka. This is general guidance, not field-specific advice.",
    keywords: ['crop', 'what to grow', 'sowing', 'kharif', 'rabi', 'soil', 'which crop', 'beleyuva'],
    questionKn: 'ಯಾವ ಬೆಳೆ ಬೆಳೆಯಬೇಕು ಮಣ್ಣಿಗೆ ಯಾವ ಬೆಳೆ ಸೂಕ್ತ',
    answerKn: "ಕೃಷಿ ಸಲಹೆ ಪುಟದಲ್ಲಿ 'Crop Recommendation' ಬಳಸಿ. ಋತು ಮತ್ತು ಮಣ್ಣಿನ ವಿಧ ಆಯ್ಕೆ ಮಾಡಿದರೆ ಸೂಕ್ತ ಬೆಳೆಗಳು ಕಾಣುತ್ತವೆ.",
    links: [{ label: 'Open Farm Advisory', to: '/agri/advisory' }] },
  { id: 'new-fertilizer', category: 'agri', question: 'How much fertilizer should I apply?',
    answer: "Use 'Fertilizer Advice' in Farm Advisory: choose the crop and your soil-test levels for nitrogen, phosphorus and potassium (low, medium, high). The portal shows the kg per acre with the calculation. It will not give a dose without soil-test data.",
    keywords: ['fertiliser', 'fertilizer', 'npk', 'urea', 'dap', 'potash', 'manure', 'gobbara'],
    questionKn: 'ಗೊಬ್ಬರ ಎಷ್ಟು ಹಾಕಬೇಕು ರಸಗೊಬ್ಬರ ಪ್ರಮಾಣ',
    answerKn: "ಕೃಷಿ ಸಲಹೆ ಪುಟದಲ್ಲಿ 'Fertilizer Advice' ತೆರೆಯಿರಿ. ಬೆಳೆ ಮತ್ತು ಮಣ್ಣು ಪರೀಕ್ಷೆಯ N, P, K ಮಟ್ಟ ನೀಡಿದರೆ ಎಕರೆಗೆ ಕೆ.ಜಿ. ಲೆಕ್ಕ ಸಿಗುತ್ತದೆ.",
    links: [{ label: 'Open Farm Advisory', to: '/agri/advisory' }] },
  { id: 'new-sellwait', category: 'agri', question: 'Should I sell my crop now or wait for a better price?',
    answer: "The 'Price Trend' tool shows whether the modal price in your district has been rising, falling or stable (needs at least 3 recorded days) and gives a plain 'sell now or wait' hint. It is a heuristic from recent prices, not a forecast.",
    keywords: ['sell', 'wait', 'harvest', 'trend', 'price rising', 'price falling', 'bele'],
    questionKn: 'ಈಗ ಮಾರಬೇಕೇ ಕಾಯಬೇಕೇ ಬೆಲೆ ಏರುತ್ತಿದೆಯೇ',
    answerKn: "'Price Trend' ಸಾಧನವು ಜಿಲ್ಲೆಯ ಬೆಲೆ ಏರುತ್ತಿದೆಯೇ ಇಳಿಯುತ್ತಿದೆಯೇ ಎಂದು ತೋರಿಸುತ್ತದೆ (ಕನಿಷ್ಠ 3 ದಿನದ ಮಾಹಿತಿ ಬೇಕು). ಇದು ಸೂಚನೆ ಮಾತ್ರ, ಖಚಿತ ಮುನ್ಸೂಚನೆ ಅಲ್ಲ.",
    links: [{ label: 'Open Farm Advisory', to: '/agri/advisory' }] },
  { id: 'new-market', category: 'agri', question: 'Which market gives me the best price for my crop?',
    answer: "Use 'Suggested Market' in Farm Advisory. It compares average prices across markets and subtracts an estimated transport cost (₹2 per km per quintal from district headquarters), then ranks markets by net price. The transport figure is an estimate.",
    keywords: ['best market', 'mandi', 'where to sell', 'transport', 'apmc', 'net price'],
    questionKn: 'ಯಾವ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಉತ್ತಮ ಬೆಲೆ ಸಿಗುತ್ತದೆ ಎಲ್ಲಿ ಮಾರಬೇಕು',
    links: [{ label: 'Open Farm Advisory', to: '/agri/advisory' }, { label: 'Live mandi prices', to: '/agri' }] },
  { id: 'new-voice', category: 'complaints', question: 'Can I report a complaint by speaking in Kannada?',
    answer: 'Yes. On the Report Issue form tap the microphone next to Description and speak in Kannada; the text is filled in for you (works in Chrome or Edge). You can also record a voice note of up to 2 minutes that officials can listen to.',
    keywords: ['voice', 'speak', 'microphone', 'mic', 'audio', 'kannada typing', 'voice note', 'record'],
    questionKn: 'ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ ದೂರು ನೀಡಬಹುದೇ ಧ್ವನಿ',
    answerKn: 'ಹೌದು. ದೂರು ಫಾರ್ಮ್ ನಲ್ಲಿ ವಿವರಣೆ ಪಕ್ಕದ ಮೈಕ್ ಬಟನ್ ಒತ್ತಿ ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ (Chrome ಅಥವಾ Edge ನಲ್ಲಿ). 2 ನಿಮಿಷದವರೆಗಿನ ಧ್ವನಿ ಸಂದೇಶವನ್ನೂ ಲಗತ್ತಿಸಬಹುದು.',
    links: [{ label: 'Report an issue', to: '/report' }] },
  { id: 'new-ai-suggest', category: 'complaints', question: 'What is the AI suggestion on the complaint form?',
    answer: 'While you type, an AI model suggests the category and priority of your complaint with a confidence percentage. It is only a suggestion; you choose whether to use it. The priority never goes below what the keyword safety rules say.',
    keywords: ['ai', 'suggestion', 'artificial intelligence', 'auto category', 'machine learning', 'predict'] },
  { id: 'new-who-fixes', category: 'complaints', question: 'Who will fix my complaint and how will I know it is really done?',
    answer: 'Your complaint goes to your district admin and the matching department. The department assigns a field worker who confirms the location, then uploads before and after photos. The department verifies the proof, marks it resolved, and you can confirm or reopen it and rate the service.',
    keywords: ['worker', 'department', 'proof', 'photo', 'resolved', 'reopen', 'confirm', 'who fixes', 'verification'],
    questionKn: 'ನನ್ನ ದೂರನ್ನು ಯಾರು ಪರಿಹರಿಸುತ್ತಾರೆ ಕೆಲಸ ಆಗಿದೆಯೇ ಹೇಗೆ ತಿಳಿಯುವುದು',
    answerKn: 'ನಿಮ್ಮ ದೂರು ಜಿಲ್ಲಾ ಅಡ್ಮಿನ್ ಮತ್ತು ಸಂಬಂಧಿತ ಇಲಾಖೆಗೆ ಹೋಗುತ್ತದೆ. ಇಲಾಖೆ ಕ್ಷೇತ್ರ ಕಾರ್ಯಕರ್ತರನ್ನು ನೇಮಿಸುತ್ತದೆ; ಅವರು ಮೊದಲು ಮತ್ತು ನಂತರದ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡುತ್ತಾರೆ. ಪರಿಹಾರವಾದ ನಂತರ ನೀವು ದೃಢೀಕರಿಸಬಹುದು ಅಥವಾ ಮತ್ತೆ ತೆರೆಯಬಹುದು.' },
  { id: 'new-track-id', category: 'complaints', question: 'How do I check the status of my complaint?',
    answer: 'Type your Tracking ID right here (it starts with SV-) and I will show the live status. You can also use the Track Complaint page without logging in.',
    keywords: ['status', 'track', 'tracking id', 'where is my complaint', 'progress', 'sv-', 'complaint number'],
    questionKn: 'ನನ್ನ ದೂರಿನ ಸ್ಥಿತಿ ಏನು ಟ್ರ್ಯಾಕಿಂಗ್ ಐಡಿ',
    answerKn: 'ನಿಮ್ಮ ಟ್ರ್ಯಾಕಿಂಗ್ ಐಡಿಯನ್ನು (SV- ಯಿಂದ ಆರಂಭ) ಇಲ್ಲಿಯೇ ಟೈಪ್ ಮಾಡಿ, ನಾನು ಸ್ಥಿತಿ ತೋರಿಸುತ್ತೇನೆ. ಅಥವಾ ಲಾಗಿನ್ ಇಲ್ಲದೆ ಟ್ರ್ಯಾಕ್ ಪುಟ ಬಳಸಿ.',
    links: [{ label: 'Track Complaint page', to: '/track' }] },
  { id: 'new-delay', category: 'complaints', question: 'What happens if my complaint is not resolved on time?',
    answer: 'Complaints are escalated automatically. A complaint left pending for about 3 days has its priority raised and admins are alerted. An SLA monitoring agent also checks department deadlines every 30 minutes and files an escalation to the district admin when a deadline is missed.',
    keywords: ['delay', 'late', 'not resolved', 'escalate', 'sla', 'no action', 'pending', 'ignored'],
    questionKn: 'ದೂರು ತಡವಾದರೆ ಏನಾಗುತ್ತದೆ ಯಾರೂ ಗಮನಿಸುತ್ತಿಲ್ಲ',
    answerKn: 'ದೂರು ಸುಮಾರು 3 ದಿನ ಬಾಕಿ ಇದ್ದರೆ ಆದ್ಯತೆ ಹೆಚ್ಚುತ್ತದೆ ಮತ್ತು ಅಡ್ಮಿನ್ ಗೆ ಎಚ್ಚರಿಕೆ ಹೋಗುತ್ತದೆ. ಇಲಾಖೆ ಗಡುವು ತಪ್ಪಿದರೆ ಸ್ವಯಂಚಾಲಿತ ಏಜೆಂಟ್ ಜಿಲ್ಲಾ ಅಡ್ಮಿನ್ ಗೆ ದೂರು ಸಲ್ಲಿಸುತ್ತದೆ.' },
  { id: 'new-roles', category: 'account', question: 'I am a field worker or department officer. How do I log in?',
    answer: 'Field worker and department accounts are created for you by your department or district admin; you cannot self-register. Log in with the mobile number or email and password you were given and you will be taken to your own dashboard.',
    keywords: ['worker login', 'department login', 'officer', 'admin login', 'staff', 'credentials', 'password given'] },
  { id: 'new-privacy', category: 'general', question: 'Is my data and are my documents safe?',
    answer: 'Documents you upload to the scheme checker are used only for the check and are deleted from the server afterwards. Voice notes are stored privately and can be played only by you, the district admin and the assigned department. Passwords are stored encrypted.',
    keywords: ['privacy', 'safe', 'secure', 'security', 'data', 'aadhaar safe', 'delete', 'confidential'],
    questionKn: 'ನನ್ನ ಮಾಹಿತಿ ಮತ್ತು ದಾಖಲೆಗಳು ಸುರಕ್ಷಿತವೇ',
    answerKn: 'ಯೋಜನೆ ಪರೀಕ್ಷೆಗೆ ನೀಡಿದ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲನೆಯ ನಂತರ ಸರ್ವರ್ ನಿಂದ ಅಳಿಸಲಾಗುತ್ತದೆ. ಧ್ವನಿ ಸಂದೇಶಗಳನ್ನು ನೀವು, ಜಿಲ್ಲಾ ಅಡ್ಮಿನ್ ಮತ್ತು ನೇಮಿತ ಇಲಾಖೆ ಮಾತ್ರ ಕೇಳಬಹುದು.' },
  { id: 'new-lang', category: 'general', question: 'Does the portal support Kannada?',
    answer: 'Yes, in several ways: speak your complaint in Kannada, upload Kannada certificates (Kannada text is read and names are matched with English), and ask this assistant in Kannada or English. The main screens are currently in English.',
    keywords: ['kannada', 'language', 'english', 'translate', 'local language'],
    questionKn: 'ಕನ್ನಡ ಬೆಂಬಲ ಇದೆಯೇ ಕನ್ನಡದಲ್ಲಿ ಬಳಸಬಹುದೇ',
    answerKn: 'ಹೌದು. ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ ದೂರು ನೀಡಬಹುದು, ಕನ್ನಡ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಬಹುದು, ಮತ್ತು ಈ ಸಹಾಯಕನನ್ನು ಕನ್ನಡದಲ್ಲಿ ಕೇಳಬಹುದು. ಮುಖ್ಯ ಪರದೆಗಳು ಸದ್ಯ ಇಂಗ್ಲಿಷ್ ನಲ್ಲಿವೆ.' },
  { id: 'new-sms', category: 'complaints', question: 'Will I get an SMS about my complaint?',
    answer: 'Yes. You receive an SMS when you submit a complaint and when its status changes or it is resolved, if SMS service is configured for the portal. The same updates appear in the notification bell inside the portal.',
    keywords: ['sms', 'message', 'notification', 'alert', 'text message', 'otp'] },
];

const FAQ = [...base, ...extra];
module.exports = { FAQ };